### ISSUE TITLE
So this isn’t supported any more?

### ISSUE THREAD

**Issue by garnern2** [custom-components/sensor.untapped#24]
I am guessing since it’s been almost 6 days since I posted my issue, and the issue from 6 months ago remains open, this isn’t supported any more with Home Assistant.

**Comment by swetoast** [comment]
it is but what you have to remember is that its limited support since both me and Ian has a life beside providing updates for this software, so in due time etc etc. 

right now my focus hasnt been HA cause balloob and the rest seems hellbent on  not providing backwards comparability with older software, there for if you upgraded it and then it broke the easy solution is to downgrade until an update is available for this software
